quiz/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('quiz/', include('quiz.urls')), 
    path('quiz/', include('quizzes.urls', namespace = 'quiz')),

]

quizzes/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'quiz'
urlpatterns = [
    # quiz views
    path('register', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.home, name='home'),
    path('student', views.student_view, name='student_view'),
    path('teacher', views.teacher_view, name='teacher_view'),
    path('subcategory_view', views.editor_view, name='editor_view'),
    path('quiz_get', views.quiz_get, name='quiz_get'),
    path('submit', views.quiz_post, name='quiz_post'),
    path('next', views.next_question, name='next_question'),
    path('reset', views.reset_quiz, name='reset_quiz'),



    path('editor/', views.editor_view, name='editor_view'),
    path('category/', views.manage_category, name='manage_category'),
    path('category/<int:category_id>/', views.manage_category, name='manage_category'),
    path('category/<int:category_id>/delete/', views.delete_category, name='delete_category'),

    path('category/<int:category_id>/subcategories/', views.subcategory_view, name='subcategory_view'),
    path('category/<int:category_id>', views.manage_subcategory, name='manage_subcategory'),
    path('subcategory/<int:subcategory_id>/delete/', views.delete_subcategory, name='delete_subcategory'),

    path('subcategory/<int:subcategory_id>/problem/', views.manage_problem, name='manage_problem'),
    #this is test for editor view 
    path('subcategory/<int:subcategory_id>/addproblem/', views.add_problem, name='add_problem'),

    path('subcategory/<int:subcategory_id>/', views.subcategory_detail, name='subcategory_detail'),

    path('student/<int:category_id>/sub_category', views.student_subcategory, name='student_subcategory'),
    path('student/sub_category/<int:subcategory_id>', views.student_problem, name='student_problem'),



    # path('subcategory/<int:subcategory_id>/problem/<int:problem_id>/', views.manage_problem, name='manage_problem'),
    path('problem/<int:problem_id>/delete/', views.delete_problem, name='delete_problem'),

]

quizzes/forms.py
# forms.py

from django import forms
from .models import Category, SubCategory, Problem
from django.forms import inlineformset_factory


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class SubCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ['name', 'category']




# class ProblemForm(forms.ModelForm):
#     class Meta:
#         model = Problem
#         fields = [ 'question_text','math_text','correct_answer','subcategory']
#         widgets = {
#             'math_text': forms.HiddenInput(),
#         }

class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ['question_text','correct_option','correct_formula', 'subcategory']

# Inline formsets
SubCategoryFormSet = inlineformset_factory(Category, SubCategory, form=SubCategoryForm, extra=1)
ProblemFormSet = inlineformset_factory(SubCategory, Problem, form=ProblemForm, extra=1)

quizzes/views.py
from .models import Category, SubCategory, Quiz, Problem, Role, UserProfile , StudentProgress
from django.http import Http404
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import CategoryForm, SubCategoryFormSet, ProblemFormSet , ProblemForm , SubCategoryForm

import random


# Create your views here.

# Registration view
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        roles = Role.objects.all()
        if form.is_valid():
            user = form.save()
            selected_role_id = request.POST.get('role')
            selected_role = Role.objects.get(id=selected_role_id)
            UserProfile.objects.create(user=user, role=selected_role)
            login(request, user)
            return redirect('quiz:home')
    else:
        form = UserCreationForm()
        roles = Role.objects.all()
    return render(request, 'user/register.html', {'form': form, 'roles': roles})


# Home view to redirect users based on their roles
@login_required
def home(request):
    user_profile = UserProfile.objects.get(user=request.user)
    print(user_profile.role.name)
    if user_profile.role.name == 'Student':
        return redirect('quiz:student_view')
    elif user_profile.role.name == 'Teacher':
        return redirect('quiz:teacher_view')
    elif user_profile.role.name == 'Editor':
        return redirect('quiz:editor_view')
    else:
        return redirect('quiz:login')


# Role-based views
@login_required
def student_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    print(user_profile.role.name)
    if user_profile.role.name == 'Student':
        categories = Category.objects.all().order_by('name')
        print(categories)
        context = {
            'categories': categories,
        }
        return render(request, 'user/student/category.html',context)
    else:
        return redirect('quiz:home')

@login_required
def student_subcategory(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    subcategories = SubCategory.objects.filter(category=category)
    completed_subcategories = []

    for subcategory in subcategories:
        total_problems = subcategory.problems.count()
        mastered_problems = StudentProgress.objects.filter(user=request.user, subcategory=subcategory, mastered=True).count()

        if total_problems == mastered_problems and total_problems > 0:
            completed_subcategories.append(subcategory.id)

    context = {
        'category': category,
        'subcategories': subcategories,
        'completed_subcategories': completed_subcategories,
    }
    return render(request, 'user/student/subcategory.html', context)



from django.http import JsonResponse

@login_required
def student_problem(request, subcategory_id):
    subcategory = get_object_or_404(SubCategory, id=subcategory_id)
    problems = Problem.objects.filter(subcategory=subcategory)

    if not problems.exists():
        return redirect('quiz:home')

    # Initialize session variables if not already set
    if 'current_problem_index' not in request.session:
        request.session['current_problem_index'] = 0
        request.session['correct_streak'] = 0
        request.session['incorrect_streak'] = 0

    current_index = request.session['current_problem_index']

    # Find the next unmastered problem
    problems_list = list(problems)
    for i in range(len(problems_list)):
        problem_index = (current_index + i) % len(problems_list)
        problem = problems_list[problem_index]
        studentprogress = StudentProgress.objects.filter(user=request.user, problem=problem).first()
        if not studentprogress or not studentprogress.mastered:
            request.session['current_problem_index'] = problem_index
            break
    else:
        # All problems have been mastered
        context = {
            'all_mastered': True,
        }
        return render(request, 'user/student/quiz_problem.html', context)

    question_text, correct_answer, params = problem.generate_dynamic_problem()

    if request.method == 'POST':
        if 'next_problem' in request.POST:
            request.session['current_problem_index'] = (current_index + 1) % len(problems_list)
            return redirect('quiz:student_problem', subcategory_id=subcategory_id)

        user_answer = request.POST.get('selected_answer')
        if user_answer == str(problem.correct_option):
            request.session['correct_streak'] += 1
            request.session['incorrect_streak'] = 0
            if request.session['correct_streak'] == 2:
                user = request.user
                student_progress, created = StudentProgress.objects.get_or_create(
                    user=user,
                    problem=problem,
                    subcategory=subcategory,
                )
                student_progress.mastered = True
                student_progress.save()
                request.session['correct_streak'] = 0
                context = {
                    'question_text': question_text,
                    'problem_id': problem.id,
                    'subcategory_id': subcategory_id,
                    'studentprogress': True,
                    'all_mastered': False,
                    'correct_formula': None,
                    'disable_submit': False,
                    'mastered': True
                }
                return render(request, 'user/student/quiz_problem.html', context)
        else:
            request.session['correct_streak'] = 0
            request.session['incorrect_streak'] += 1
            if request.session['incorrect_streak'] == 2:
                request.session['incorrect_streak'] = 0
                context = {
                    'question_text': question_text,
                    'problem_id': problem.id,
                    'subcategory_id': subcategory_id,
                    'studentprogress': False,
                    'all_mastered': False,
                    'correct_formula': problem.correct_formula,
                    'disable_submit': True,
                    'correct_option':problem.correct_option,

                    
                }
                return render(request, 'user/student/quiz_problem.html', context)
        return redirect('quiz:student_problem', subcategory_id=subcategory_id)
    
    context = {
        'question_text': question_text,
        'problem_id': problem.id,
        'subcategory_id': subcategory_id,
        'studentprogress': False,
        'all_mastered': False,
        'correct_formula': None,
        'disable_submit': False,
        'mastered': False,
        'correct_option':problem.correct_option,
    }

    return render(request, 'user/student/quiz_problem.html', context)



@login_required
def teacher_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    if user_profile.role.name == 'Teacher':
        return render(request, 'user/teacher.html')
    else:
        return redirect('quiz:home')


@login_required
def editor_view(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'user/editor/editor_view.html', context)

@login_required
def subcategory_view(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    print(category)
    subcategories = SubCategory.objects.filter(category=category)
    context = {
        'category': category,
        'subcategories': subcategories,
    }
    return render(request, 'user/editor/subcategory_view.html', context)




@login_required
def manage_category(request, category_id=None):
    if category_id:
        category = get_object_or_404(Category, id=category_id)
    else:
        category = Category()

    if request.method == 'POST':
        category_form = CategoryForm(request.POST, instance=category)
        subcategory_formset = SubCategoryFormSet(request.POST, instance=category)

        if category_form.is_valid() and subcategory_formset.is_valid():
            category_form.save()
            subcategory_formset.save()
            return redirect('quiz:editor_view')
    else:
        category_form = CategoryForm(instance=category)
        subcategory_formset = SubCategoryFormSet(instance=category)

    return render(request, 'user/editor/manage_category.html', {
        'category_form': category_form,
        'subcategory_formset': subcategory_formset,
    })


@login_required

def manage_subcategory(request, category_id):
    print(category_id)
    category = Category.objects.get(id=category_id)

    if request.method == 'POST':
        subcategory_form = SubCategoryForm(request.POST)
        if subcategory_form.is_valid():
            subcategory = subcategory_form.save(commit=False)
            subcategory.category = category  # Assign category to the subcategory
            subcategory.save()
            return redirect('quiz:subcategory_detail', subcategory_id=subcategory.id)
    else:
        subcategory_form = SubCategoryForm()

    return render(request, 'user/editor/manage_subcategory.html', {
        'subcategory_form': subcategory_form,
        'category': category,
    })


@login_required

def manage_problem(request, subcategory_id):
    subcategory = SubCategory.objects.get(id=subcategory_id)
    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            problem.subcategory = subcategory
            problem.save()
            if request.POST.get('action') == 'add_another':
                print("Problem saved successfully. Redirecting to manage_problem view.")

quizzes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Quiz Application{% endblock %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    

    <link href="{% static "css/quiz.css" %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <div class="navbar-brand">Quiz Application</div>
            <ul class="navbar-links">
                <li><a href="{% url 'quiz:home' %}">Home</a></li>
                <li><a href="{% url 'quiz:quiz_get' %}">Quizzes</a></li>
                {% if user.is_authenticated %}
                    <li><a href="#">Welcome, {{ user.username }}</a></li>
                    <li>
                        <form action="{% url 'quiz:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                {% else %}
                    <li><a href="{% url 'quiz:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div id="content">
        {% block content %}
        {% endblock %}

    </div>
    <div id="footer">
        <p>&copy; 2024 Quiz Application. All rights reserved.</p>
    </div>
</body>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        MathJax.typeset();
    });
</script>



  
<!-- KaTeX CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.18/katex.min.css">

<!-- KaTeX JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.18/katex.min.js"></script>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script type="text/javascript"  src="/static/vendors/handlebars.min-latest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!--CHECK THIS-->
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0/dist/js.cookie.min.js"></script>
<script type="text/javascript" src="/static/js/script.js"></script>
<script type="text/javascript" src="/static/js/remote.js"></script>
<script type="text/javascript" src="/static/js/templating.js"></script>
<script type="text/javascript" src="/static/popup.js"></script>
</html>

quizzes/templates/end.html
{% extends 'base.html' %}

{% block title %}
Quiz List
{% endblock %}

{% block content %}
<body>
    <div class="container">
        
        <div class="card">
            <h1>Quiz Completed!</h1>
            <p>Your final score is: {{ score }} / {{q_no}}</p>
            <button ><a href="{% url 'quiz:reset_quiz' %}">Restart Quiz</a></button>
        </div>
    </div>
</body>
</html>
{% endblock %}

quizzes/templates/list.html
{% extends 'base.html' %}

{% block title %}
Quiz List
{% endblock %}

{% block content %}
    <div class="card" id="quiz-card">
        <div id="container">
            <p style="font-weight: bold;"> Question {{question_number}}</p>
            {% if question_type == 'true_false' %}
                <h3>{{ question }}</h3>
                <form action="{% url 'quiz:quiz_post' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label>
                        <input type="radio" onclick="checkAnswer()" name="answer" value="True"> True
                    </label>
                    <label>
                        <input type="radio" onclick="checkAnswer()" name="answer" value="False"> False
                    </label>
                    <input type="hidden" id="selected_answer" name="selected_answer" value="">
                    <div id="feedback" style="display: none; margin-top: 10px;"></div>

                    <button type="submit">Submit</button>
                </form>
            {% elif question_type == 'equation' %}
                <h3>Solve the equation: {{ equation }}</h3>
                <form id = "equation_form" action="{% url 'quiz:quiz_post' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="answer">x = </label>
                    <input type="number" id="eq_answer"  name="eq_answer" required>
                    <div id="feedback" style="display: none; margin-top: 10px;"></div>
                    <input type="hidden" id="selected_answer" name="selected_answer" value="">
                    <button type="button" id="check" onclick="replaceButton()">Check</button>
                </form>
            {% endif %}
        </div>

        <script>
            var question_type = "{{ question_type|safe }}";
            console.log(question_type)
            var correctAnswer = "{{ correct_answer|safe }}";
            console.log(correctAnswer)
            if (question_type == 'true_false' ){
                function checkAnswer() {
                    const radios = document.getElementsByName('answer');
                    let selectedValue;
                    for (const radio of radios) {
                        if (radio.checked) {
                            selectedValue = radio.value;
                            break;
                        }
                    }
                    if (selectedValue === correctAnswer) {
                        document.getElementById('feedback').innerText = 'Correct';
                    } else {
                        document.getElementById('feedback').innerText = 'Incorrect';
                    }
                    for (const radio of radios) {
                        radio.disabled = true;
                    }
                    document.getElementById('selected_answer').value = selectedValue;
                    document.getElementById('feedback').style.display = 'block';
                }
            }
            else(question_type == 'equation')
            {
                function replaceButton() {
                    // Disable and hide the existing button with id = check
                    let ans = document.getElementById('eq_answer').value;
                    console.log("user answer",ans)
                    if (ans === correctAnswer) {
                        document.getElementById('feedback').innerText = 'Correct';
                    } else {
                        document.getElementById('feedback').innerText = 'Incorrect';
                    }
                    var checkButton = document.getElementById('check');
                    checkButton.disabled = true;
                    checkButton.style.display = 'none';

                    var answerInput = document.getElementById('eq_answer');
                    answerInput.disabled = true;
                    document.getElementById('feedback').style.display = 'block';
                    document.getElementById('selected_answer').value = ans;
                    // Create a new submit button
                    var submitButton = document.createElement('button');
                    submitButton.setAttribute('type', 'submit');
                    submitButton.innerText = 'Submit';

                    // Add event listener to submit button to submit the form
                    submitButton.addEventListener('click', function(event) {
                        // Submit the form with id = equation_form
                        document.getElementById('equation_form').submit();
                    });

                    // Append the new submit button to the form
                    var form = document.getElementById('equation_form');
                    form.appendChild(submitButton);
                }
            }
        </script>
    </div>
{% endblock %}

quizzes/templates/start.html
{% extends 'base.html' %}

{% block title %}
Quiz List
{% endblock %}

{% block content %}
<head>
    <title>Quiz Time!</title>
    <style>

    </style>
</head>

    <div class="container">
        <h1>Welcome to the Quiz!</h1>
        <div class="card">
            <p>Do you want to start the quiz?</p>
            <button id="startButton"><a href="{% url 'quiz:quiz_get' %}">Quizzes</a></button>
        </div>
    </div>

{% endblock %}