quiz/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('quiz/', include('quiz.urls')), 
    path('quiz/', include('quizzes.urls', namespace = 'quiz')),

]

quizzes/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'quiz'
urlpatterns = [
    # quiz views
    path('register', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.home, name='home'),
    path('student', views.student_view, name='student_view'),
    path('teacher', views.teacher_view, name='teacher_view'),
    path('subcategory_view', views.editor_view, name='editor_view'),
    path('quiz_get', views.quiz_get, name='quiz_get'),
    path('submit', views.quiz_post, name='quiz_post'),
    path('next', views.next_question, name='next_question'),
    path('reset', views.reset_quiz, name='reset_quiz'),



    path('editor/', views.editor_view, name='editor_view'),
    path('category/', views.manage_category, name='manage_category'),
    path('category/<int:category_id>/', views.manage_category, name='manage_category'),
    path('category/<int:category_id>/delete/', views.delete_category, name='delete_category'),

    path('category/<int:category_id>/subcategories/', views.subcategory_view, name='subcategory_view'),
    path('category/<int:category_id>', views.manage_subcategory, name='manage_subcategory'),
    path('subcategory/<int:subcategory_id>/delete/', views.delete_subcategory, name='delete_subcategory'),

    path('subcategory/<int:subcategory_id>/problem/', views.manage_problem, name='manage_problem'),
    #this is test for editor view 
    path('subcategory/<int:subcategory_id>/addproblem/', views.add_problem, name='add_problem'),

    path('subcategory/<int:subcategory_id>/', views.subcategory_detail, name='subcategory_detail'),

    path('student/<int:category_id>/sub_category', views.student_subcategory, name='student_subcategory'),
    path('student/sub_category/<int:subcategory_id>', views.student_problem, name='student_problem'),



    # path('subcategory/<int:subcategory_id>/problem/<int:problem_id>/', views.manage_problem, name='manage_problem'),
    path('problem/<int:problem_id>/delete/', views.delete_problem, name='delete_problem'),

]

quizzes/forms.py
# forms.py

from django import forms
from .models import Category, SubCategory, Problem
from django.forms import inlineformset_factory


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class SubCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ['name', 'category']




# class ProblemForm(forms.ModelForm):
#     class Meta:
#         model = Problem
#         fields = [ 'question_text','math_text','correct_answer','subcategory']
#         widgets = {
#             'math_text': forms.HiddenInput(),
#         }

class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ['question_text','correct_option','correct_formula', 'subcategory']

# Inline formsets
SubCategoryFormSet = inlineformset_factory(Category, SubCategory, form=SubCategoryForm, extra=1)
ProblemFormSet = inlineformset_factory(SubCategory, Problem, form=ProblemForm, extra=1)

quizzes/views.py
from .models import Category, SubCategory, Quiz, Problem, Role, UserProfile , StudentProgress
from django.http import Http404
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import CategoryForm, SubCategoryFormSet, ProblemFormSet , ProblemForm , SubCategoryForm

import random


# Create your views here.

# Registration view
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        roles = Role.objects.all()
        if form.is_valid():
            user = form.save()
            selected_role_id = request.POST.get('role')
            selected_role = Role.objects.get(id=selected_role_id)
            UserProfile.objects.create(user=user, role=selected_role)
            login(request, user)
            return redirect('quiz:home')
    else:
        form = UserCreationForm()
        roles = Role.objects.all()
    return render(request, 'user/register.html', {'form': form, 'roles': roles})


# Home view to redirect users based on their roles
@login_required
def home(request):
    user_profile = UserProfile.objects.get(user=request.user)
    print(user_profile.role.name)
    if user_profile.role.name == 'Student':
        return redirect('quiz:student_view')
    elif user_profile.role.name == 'Teacher':
        return redirect('quiz:teacher_view')
    elif user_profile.role.name == 'Editor':
        return redirect('quiz:editor_view')
    else:
        return redirect('quiz:login')


# Role-based views
@login_required
def student_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    print(user_profile.role.name)
    if user_profile.role.name == 'Student':
        categories = Category.objects.all().order_by('name')
        print(categories)
        context = {
            'categories': categories,
        }
        return render(request, 'user/student/category.html',context)
    else:
        return redirect('quiz:home')

@login_required
def student_subcategory(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    subcategories = SubCategory.objects.filter(category=category)
    completed_subcategories = []

    for subcategory in subcategories:
        total_problems = subcategory.problems.count()
        mastered_problems = StudentProgress.objects.filter(user=request.user, subcategory=subcategory, mastered=True).count()

        if total_problems == mastered_problems and total_problems > 0:
            completed_subcategories.append(subcategory.id)

    context = {
        'category': category,
        'subcategories': subcategories,
        'completed_subcategories': completed_subcategories,
    }
    return render(request, 'user/student/subcategory.html', context)



from django.http import JsonResponse

@login_required
def student_problem(request, subcategory_id):
    subcategory = get_object_or_404(SubCategory, id=subcategory_id)
    problems = Problem.objects.filter(subcategory=subcategory)

    if not problems.exists():
        return redirect('quiz:home')

    # Initialize session variables if not already set
    if 'current_problem_index' not in request.session:
        request.session['current_problem_index'] = 0
        request.session['correct_streak'] = 0
        request.session['incorrect_streak'] = 0

    current_index = request.session['current_problem_index']

    # Find the next unmastered problem
    problems_list = list(problems)
    for i in range(len(problems_list)):
        problem_index = (current_index + i) % len(problems_list)
        problem = problems_list[problem_index]
        studentprogress = StudentProgress.objects.filter(user=request.user, problem=problem).first()
        if not studentprogress or not studentprogress.mastered:
            request.session['current_problem_index'] = problem_index
            break
    else:
        # All problems have been mastered
        context = {
            'all_mastered': True,
        }
        return render(request, 'user/student/quiz_problem.html', context)

    question_text, correct_answer, params = problem.generate_dynamic_problem()

    if request.method == 'POST':
        if 'next_problem' in request.POST:
            request.session['current_problem_index'] = (current_index + 1) % len(problems_list)
            return redirect('quiz:student_problem', subcategory_id=subcategory_id)

        user_answer = request.POST.get('selected_answer')
        if user_answer == str(problem.correct_option):
            request.session['correct_streak'] += 1
            request.session['incorrect_streak'] = 0
            if request.session['correct_streak'] == 2:
                user = request.user
                student_progress, created = StudentProgress.objects.get_or_create(
                    user=user,
                    problem=problem,
                    subcategory=subcategory,
                )
                student_progress.mastered = True
                student_progress.save()
                request.session['correct_streak'] = 0
                context = {
                    'question_text': question_text,
                    'problem_id': problem.id,
                    'subcategory_id': subcategory_id,
                    'studentprogress': True,
                    'all_mastered': False,
                    'correct_formula': None,
                    'disable_submit': False,
                    'mastered': True
                }
                return render(request, 'user/student/quiz_problem.html', context)
        else:
            request.session['correct_streak'] = 0
            request.session['incorrect_streak'] += 1
            if request.session['incorrect_streak'] == 2:
                request.session['incorrect_streak'] = 0
                context = {
                    'question_text': question_text,
                    'problem_id': problem.id,
                    'subcategory_id': subcategory_id,
                    'studentprogress': False,
                    'all_mastered': False,
                    'correct_formula': problem.correct_formula,
                    'disable_submit': True,
                    'correct_option':problem.correct_option,

                    
                }
                return render(request, 'user/student/quiz_problem.html', context)
        return redirect('quiz:student_problem', subcategory_id=subcategory_id)
    
    context = {
        'question_text': question_text,
        'problem_id': problem.id,
        'subcategory_id': subcategory_id,
        'studentprogress': False,
        'all_mastered': False,
        'correct_formula': None,
        'disable_submit': False,
        'mastered': False,
        'correct_option':problem.correct_option,
    }

    return render(request, 'user/student/quiz_problem.html', context)



@login_required
def teacher_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    if user_profile.role.name == 'Teacher':
        return render(request, 'user/teacher.html')
    else:
        return redirect('quiz:home')


@login_required
def editor_view(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'user/editor/editor_view.html', context)

@login_required
def subcategory_view(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    print(category)
    subcategories = SubCategory.objects.filter(category=category)
    context = {
        'category': category,
        'subcategories': subcategories,
    }
    return render(request, 'user/editor/subcategory_view.html', context)




@login_required
def manage_category(request, category_id=None):
    if category_id:
        category = get_object_or_404(Category, id=category_id)
    else:
        category = Category()

    if request.method == 'POST':
        category_form = CategoryForm(request.POST, instance=category)
        subcategory_formset = SubCategoryFormSet(request.POST, instance=category)

        if category_form.is_valid() and subcategory_formset.is_valid():
            category_form.save()
            subcategory_formset.save()
            return redirect('quiz:editor_view')
    else:
        category_form = CategoryForm(instance=category)
        subcategory_formset = SubCategoryFormSet(instance=category)

    return render(request, 'user/editor/manage_category.html', {
        'category_form': category_form,
        'subcategory_formset': subcategory_formset,
    })


@login_required

def manage_subcategory(request, category_id):
    print(category_id)
    category = Category.objects.get(id=category_id)

    if request.method == 'POST':
        subcategory_form = SubCategoryForm(request.POST)
        if subcategory_form.is_valid():
            subcategory = subcategory_form.save(commit=False)
            subcategory.category = category  # Assign category to the subcategory
            subcategory.save()
            return redirect('quiz:subcategory_detail', subcategory_id=subcategory.id)
    else:
        subcategory_form = SubCategoryForm()

    return render(request, 'user/editor/manage_subcategory.html', {
        'subcategory_form': subcategory_form,
        'category': category,
    })


@login_required

def manage_problem(request, subcategory_id):
    subcategory = SubCategory.objects.get(id=subcategory_id)
    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            problem.subcategory = subcategory
            problem.save()
            if request.POST.get('action') == 'add_another':
                print("Problem saved successfully. Redirecting to manage_problem view.")

quizzes/templates/user/student/category.html
{% extends 'base.html' %}

{% block title %}
Student Category
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Categories</h2>
    <ul class="list-group mb-5">
        {% for category in categories %}
            <li class="list-group-item">
                <a href="{% url 'quiz:student_subcategory' category.id %}">{{ category.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

quizzes/templates/user/student/quiz_problem.html
{% extends 'base.html' %}

{% block title %}
Student Category
{% endblock %}

{% block content %}
<!-- KaTeX CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.18/katex.min.css">

<!-- KaTeX JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.18/katex.min.js"></script>

{% if all_mastered %}
<div class="container mt-5">
    <p>All problems in this subcategory have been mastered. No more problems left.</p>
    <a href="{% url 'quiz:home' %}" class="btn btn-primary">Return to Home</a>
</div>
{% else %}
<div class="container mt-5">
    {% if mastered %}
    <div class="alert alert-success">
        <p>Congratulations! You have mastered this problem.</p>
    </div>
    {% endif %}

    {% if not mastered %}
    <h2>Quiz Problem</h2>
    <div id="quiz-content">
        <h3>Is it True or False?</h3>

        <p id="question-text"></p>
        <p id="math_test"></p>

        <form id="quiz-form" method="post" action="">
            {% csrf_token %}
            <div class="form-group">
                <label for="answer">Your Answer</label>
                <select class="form-control" id="answer" name="answer"  onchange="checkAnswer()" required >
                    <option value="">Select an answer</option>
                    <option value="True">True</option>
                    <option value="False">False</option>
                </select>
                <input id="selected_answer" name="selected_answer" value="" hidden>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div id="result" class="mt-3" style="display: none;">
        <h2>Result</h2>
        <p id="result-text"></p>
    </div>
    {% endif %}

    {% if correct_formula %}
    <div class="mt-3">
        <h2>Correct Formula</h2>
        <p id="correct_formula"></p>
    </div>
    {% endif %}

    {% if mastered or answer_checked %}
    <form method="post" action="">
        {% csrf_token %}
        <input type="hidden" name="next_problem" value="true">
        <button id="next-problem-btn" class="btn btn-primary mt-3">Move to Next Problem</button>
    </form>
    {% endif %}
</div>
{% endif %}

<script>
document.addEventListener('DOMContentLoaded', function() {
    const mathTextRenderContainer = document.getElementById('math_test');
    const questionText = '{{ question_text|escapejs }}';
    if (questionText) {
        mathTextRenderContainer.innerHTML = katex.renderToString(questionText);
    } else {
        console.error('No question text found');
    }

    const correctformulaRenderContainer = document.getElementById('correct_formula');
    const correctFormula = '{{ correct_formula|escapejs }}';
    if (correctFormula) {
        correctformulaRenderContainer.innerHTML = katex.renderToString(correctFormula);
    } else {
        console.error('No correct formula text found');
    }
});

function checkAnswer() {
    const answerSelect = document.getElementById('answer');
    const send_answer = document.getElementById('selected_answer');

    const selectedAnswer = answerSelect.value;
    const correctAnswer = '{{ correct_option|safe }}';
    console.log(correctAnswer)
    console.log(selectedAnswer)
    const resultDiv = document.getElementById('result');
    const resultText = document.getElementById('result-text');
    if (!resultText) {
        console.error('result-text element not found');
        return;
    }

    if (!resultDiv) {
        console.error('result element not found');
        return;
    }

    if (selectedAnswer) {
        if (selectedAnswer === correctAnswer) {
            resultText.textContent = 'Your answer is correct!';
            resultText.className = 'text-success';
        } else {
            resultText.textContent = 'Your answer is incorrect.';
            resultText.className = 'text-danger';
        }
        answerSelect.disabled = true;
        send_answer.value = selectedAnswer;
        resultDiv.style.display = 'block';
    } else {
        resultDiv.style.display = 'none';
    }
}
</script>

{% endblock %}

quizzes/templates/user/student/subcategory.html
{% extends 'base.html' %}

{% block title %}
Student Subcategory
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>{{ category.name }} Subcategories</h2>
    <ul class="list-group mb-5">
        {% for subcategory in subcategories %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'quiz:student_problem' subcategory.id %}">{{ subcategory.name }}</a>

                {% if subcategory.id in completed_subcategories %}
                    <span class="badge badge-success">Completed</span>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}